### PR TITLE
New Feature: HTML Plugins

### PR DESCRIPTION
**Pull request by muhqu**
This Pull Request is a WIP.

The idea ist to place HTML files into the Plugin Folder and render them as tiny WebViews. The HTML should be allowed to execute JavaScript, make AJAX Requests, load local files(?)... etc.

What do you think?

Example:
bitbar webview-1

### CODE REVIEW

**Comment by dzg** [comment]
Is it possible to use HTML plugins?
I tried an .html in the bitbar folder, and it renders, but doesn't respond to clicks.
Are dropdowns possible?

**Comment by matryer** [comment]
They’re not really supported… to be honest, they wouldn’t be very good—and it would be too easy to build horrible plugins, so there isn’t much appetite to have them.

What are you trying to do that you can’t do with just text?

**Comment by dzg** [comment]
I'm writing a plugin that pulls my financial data from Mint, and shows accounts, balances, transactions, etc. (which I'll be happy to share when complete.)

But it's a hell of a time getting the tables to format nicely, and I'd really like to be able to change the color of individual words, not just entire lines. HTML tables would be much easier to generate and style.

It would also be awesome to have an ajax type dynamic search box.

**Comment by frakman1** [comment]
@dzg 
> (which I'll be happy to share when complete.)

Would you mind sharing it now even if it's not complete?
By the way, you can change individual words using ANSI control codes.

**Comment by dzg** [comment]
> @dzg
> 
> > (which I'll be happy to share when complete.)
> 
> Would you mind sharing it now even if it's not complete?
> By the way, you can change individual words using ANSI control codes.

I've since switched to using Buxfer.com API (it's much easier to grab data) ... LMK if you're still interested.

**Comment by frakman1** [comment]
> I've since switched to using Buxfer.com API (it's much easier to grab data) ... LMK if you're still interested.

Yes, definitely still interested.

**Comment by dzg** [comment]
> > I've since switched to using Buxfer.com API (it's much easier to grab data) ... LMK if you're still interested.
> 
> Yes, definitely still interested.

@frakman1 Here you go: https://gist.github.com/dzg/c208731bbb1bfff2e1c3e0385a51448d

_Caveats:_

1. Lately Buxfer has started rate limiting API calls; but I don't know the limits, so there's a timeout. Sometimes it just fails.
2. The chunk at line 61 (which figures out account type for display) needs work, to handle unlisted accounts.
3. You'll need to tweak the code to match your Buxfer setup with regard to account names, etc.
4. Sorry, it's messy code (for personal use)
5. Eventually I – or someone – will package this as a proper plugin!

**Pull request merged**
