### PR TITLE
use iTerm app

### PR DESCRIPTION
**Pull request by ElRochito**

### CODE REVIEW

**Comment by tresni** [comment]
I wouldn't change `terminal=` to have a new meaning. It means everyone's existing scripts would break. I would just add the `iterm=` if and let it fall through to the old behavior if it's not there. 

Just my $.02

**Comment by julio6114** [comment]
pull request updated
I remove background property, if iterm property was not net, the old behavior process

**Comment by tresni** [comment]
Looks good to me. I'll give it a shot when I get to a computer tonight.

**Comment by tresni** [comment]
Okay, my only complaint is that I have to set `iterm=true` for everything...  And plugin developers need to be careful as if you do this and the end user doesn't have iTerm then the command will fail silently.  Instead, may make more sense to make this a user level preference.

What about something like:

```diff
diff --git a/App/BitBar/NSUserDefaults+Settings.h b/App/BitBar/NSUserDefaults+Settings.h
index cb55ddd..aff9ea0 100644
--- a/App/BitBar/NSUserDefaults+Settings.h
+++ b/App/BitBar/NSUserDefaults+Settings.h
@@ -12,6 +12,7 @@

 @property NSString* pluginsDirectory;
 @property BOOL isFirstTimeAppRun;
+@property (readonly) BOOL useiTerm;

 @end

diff --git a/App/BitBar/NSUserDefaults+Settings.m b/App/BitBar/NSUserDefaults+Settings.m
index 1bc889f..4ab554f 100644
--- a/App/BitBar/NSUserDefaults+Settings.m
+++ b/App/BitBar/NSUserDefaults+Settings.m
@@ -24,5 +24,7 @@
   [self setBool:firstTime forKey:@"appHasRun"];
 }

+- (BOOL) useiTerm { return [self boolForKey:@"useiTerm"]; }
+
 @end

diff --git a/App/BitBar/Plugin.m b/App/BitBar/Plugin.m
index aac42db..32ff336 100644
--- a/App/BitBar/Plugin.m
+++ b/App/BitBar/Plugin.m
@@ -11,6 +11,7 @@
 #import "STPrivilegedTask.h"
 #import "NSDate+DateTools.h"
 #import "NSColor+Hex.h"
+#import "NSUserDefaults+Settings.h"

 #define DEFAULT_TIME_INTERVAL_SECONDS ((double)60.)

@@ -153,8 +154,7 @@
            *param3 = params[@"param3"] ?: @"",
            *param4 = params[@"param4"] ?: @"",
            *param5 = params[@"param5"] ?: @"",
-         *terminal = params[@"terminal"] ?: [NSString stringWithFormat:@"%s", "true"],
-         *iterm = params[@"iterm"] ?: [NSString stringWithFormat:@"%s", "false"];
+  *terminal = params[@"terminal"] ?: [NSString stringWithFormat:@"%s", "true"];
     NSArray *args = params[@"args"] ?: ({

       NSMutableArray *argArray = @[].mutableCopy;
@@ -190,7 +190,7 @@
       NSString *full_link = [NSString stringWithFormat:@"%@ %@ %@ %@ %@ %@", bash, param1, param2, param3, param4, param5];
       NSString *full_link_no_end_space = [full_link stringByTrimmingCharactersInSet: [NSCharacterSet whitespaceCharacterSet]];

-      if([iterm isEqual: @"true"]){
+      if(DEFS.useiTerm){
           NSString *sIterm = [NSString stringWithFormat:@"tell application \"iTerm\" \n\
                         activate \n\
                         set myterm to (make new terminal) \n\
```

Can be set with:

```
defaults write com.matryer.BitBar useiTerm -bool YES
```

Also, this fails with iTerm 2.9-beta as they are changing applescript handling... Had to downgrade to 2.1 to test this :)

**Comment by tresni** [comment]
:+1:

**Comment by matryer** [comment]
Would it be better to instead specify the terminal app to use? Rather than hard-coding iTerm in?

**Comment by tresni** [comment]
You could read the invoked AppleScript from a preference.  (That is the behavior that [Alfred.app went with](https://www.alfredapp.com/help/features/terminal/) BTW to solve the iTerm 2.1/2.9 issue, also offers support for any other terminal app via applescript or command invocation.)

It's a little harder to manage since there is no preference GUI, but totally doable.

**Comment by matryer** [comment]
What if it became an option in the Preferences menu? `"Choose terminal app..."` or similar.

**Comment by tresni** [comment]
You'd need to know how to invoke each possible app.  Which means either you still have all the AppleScript strings hard coded or you have someplace that people enter the appropriate applescript

**Comment by tresni** [comment]
@matryer Are you looking for something similar to the tresni@fc59aa0 commit above?  You can use this with iTerm 2.9 by running the following:

```sh
defaults write com.matryer.BitBar terminalScript -string 'tell application "iTerm"
        activate
        try
                select first window
                set onlywindow to false
        on error
                create window with default profile
                select first window
                set onlywindow to true
        end try
        tell the first window
                if onlywindow is false then
                        create tab with default profile
                end if
                tell current session to write text "%@"
        end tell
end tell'
```

Still defaults to the existing Terminal script(s).

**Comment by joshstrange** [comment]
@tresni Will that applescript snippet you posted work with 2.1 or just 2.9? Also what can you run to revert that change?

**Comment by tresni** [comment]
@joshstrange Just 2.9, for 2.1 you'd use something like:
```bash
defaults write com.matryer.BitBar terminalScript -string 'tell application "iTerm"
    activate
    set myterm to (make new terminal)
    tell myterm
        my open_tab("%@")
    end tell
end tell
 on open_tab(command)
    set commands to paragraphs in command
    tell application "iTerm" to tell first terminal
        launch session "Default Session"
        repeat with currentCommand in commands
            tell last session to write text currentCommand
        end repeat
    end tell
 end open_tab'
```

I haven't tested this, it's an exact copy from @julio6114 commit :)

**Comment by joshstrange** [comment]
Hmm, that didn't do the trick for me but that's for trying! (It asked for accessibility control, which I gave it but to no avail)

I'll just keep an eye on this issue.

Also it didn't cause any issues but to remove it you would use:

    defaults delete com.matryer.BitBar terminalScript

**Comment by vogonistic** [comment]
What if we write the script to a file with the extension `.command` and open it? That way you can change iTerm to handle `.command` files and have it run there. I've tested associating `.command` with iTerm, and it works for me.

**Pull request closed without merging**
