### PR TITLE
Partially fixes #480 by avoiding a full plugin manager reset...

### LINKED ISSUE #480: Keeps losing position in menu bar
Since at least Sierra, macOS lets us command-drag an item in the menu bar to a non-default position. BitBar menu bar items keep losing the custom position given by command-dragging however. Is there any way to prevent this?

### PR DESCRIPTION
**Pull request by sohocoke**
… when system wakes from sleep; fix label for reset menu item for reset since it wasn't a simple refresh.

### CODE REVIEW

**Comment by xilopaint** [comment]
This is a very welcome PR. I hope it can be merged soon and others PRs can also be reviewed by @gingerbeardman and other maintainers.

**Comment by gingerbeardman** [comment]
I'm trying to get to the bottom of Travis CI failing consistently

**Comment by gingerbeardman** [comment]
Still no idea on Travis, but I'm running this build 24/7 now to see how it fares.

**Comment by sohocoke** [comment]
> Still no idea on Travis, but I'm running this build 24/7 now to see how it fares.
Re the build, did you have a chance to confirm that "$CERT_PW” has been set to the passphrase in the build environment? The other environment variables used in the line that fails the build all seem to be values set prior in the script, so “$CERT_PW” looks suspicious.

**Comment by gingerbeardman** [comment]
I'll check and raise it with the owner

**Comment by gingerbeardman** [comment]
Here's an unsigned build with this fix.

Note: it will complain every time it tries to do a sparkle update.

[BitBar.app.zip](https://github.com/matryer/bitbar/files/4317678/BitBar.app.zip)

**Comment by dylanrossmurphy** [comment]
Fantastic! Thank you.

**Comment by frakman1** [comment]
@gingerbeardman Is this fix available in the beta branch and can a release be made for it? It's been a long time since it was tagged.

Also, did you manage to get the Travis signing thing to work? [My PR](https://github.com/matryer/bitbar/pull/431) wouldn't go through either because of it.

Finally, how did you get the unsigned image? Is it an intermediate artifact of the Travis CI build or did you have to build it yourself?

**Comment by gingerbeardman** [comment]
@frakman1 there's a build just a little earlier in the comments on this issue: https://github.com/matryer/bitbar/pull/502#issuecomment-597561941

Other maintainers will be able to help you on the other things.

**Comment by frakman1** [comment]
> @frakman1 there's a build just a little earlier in the comments on this issue: #502 (comment)

Yes, I was referring specifically to this comment that you posted. Is it available in the beta branch too or only in the master branch? It seems only master.

Since you posted that comment and the zip file, I was asking you how you got it.

**Comment by gingerbeardman** [comment]
@frakman1 I built the source that this PR includes. See `bigbearlabs:master` link at the top of the page.

**Comment by frakman1** [comment]
Thanks. I tried it. For whatever reason, this version of BitBar won't render my base64 icon and displays an empty/invisible string. It would show an emoji or other text and even a different base64 icon. For some reason, it doesn't like my icon (my icon works works with the official build BitBar). Same behavior after a restart of app and Mac.

I can confirm, however, that it doesn't move after a sleep/wakeup event.

**Comment by gingerbeardman** [comment]
@frakman1 great to hear! you could try redoing your base64 icon (for example by optimising the source image using ImageOptim and then converting the result again) as slightly different data may work. Just an idea.

**Comment by nash8114** [comment]
On macOS 10.15.7 the trick with renaming does not work as expected. The order of the items in the top bar appears to be unrelated to the file name, but rather determined by inode number (right-most being the lowest inode). Every time I've refreshed the bitbar, scripts are displayed in inode order.

The inconsistent results (working for some people but not for others) can be explained by people using either symlinks or script files directly. When renaming a regular file, it does not get a new inode number. When renaming a symlink, a new inode is created.

A consistent way to set the order (tested with scripts that all have the same refresh rate) is to make symlinks to the script files in the correct order. Rightmost item symlink should be created first. If you prefer to use script files directly without linking, then use cp to copy each file in the correct order. Use `ls -1i | sort -n` to check whether the order is correct.

**Pull request closed without merging**
