### PR TITLE
[WIP] Migrate to Swift

### PR DESCRIPTION
**Pull request by oleander**
This pull request aims to add support for Swift 3. It's based up-on the beta branch and implements support for all parameters described in the README. The main goal has been to modernize the application stack by implementing a combinatory LL parser verified using property-based testing.

## The parser

The parser, the piece of software responsible for processing script outputs, is implemented using the [FootlessParser](https://github.com/kareman/FootlessParser) parser and is located in `App/BitBar/Parser/Parser.swift`. It's build up-on 50+ smaller parser (hence the name; parser combinator), such as `Length.init <^> attribute("length") { digits() }` for parsing the length attribute (`length=X`).

The parser is context aware and will handle nested sub menus as well as invalid arguments, i.e `length=false`. One of the major benefits of using a parser like this ability to generate easy-to-understand error messages much similar to those generated by a compiler/transpiler. This makes implementing plugins easier as errors are caught and raised early. An example is `Expected 'a number' on 3:12, but got 'false'` when passing `length=false`.

## Testing

The parser is verified using the [SwiftCheck](https://github.com/typelift/SwiftCheck) library, a property-based testing framework for generating test data. The current test suit is ran against 1400 random examples.

The rest of the implementation is partially tested (about 80 tests) using the [Quick](https://github.com/Quick/Quick) testing framework.

Run `make test` to run the suit once or `make watch` to run `make test` each time a file is changed. Don't forget to install the dependencies listed below.

The application is ready for travis-ci and the latest builds can be found [here](https://travis-ci.org/oleander/bitbar/builds).

## Dependencies

I've tried to "out source" as much of the implementation as possible to external libraries using CocoaPods. There's currently 11 dependencies which can be found the in the `App/Podfile` file. They are automatically installed when running `make deps`.

## How to use

1. Clone the project
2. Install project dependencies using
    1. `gem install cocoapods xcpretty`
    2. `make deps` to install the pods
2. Run tests suit using `make test`
3. Build and run using XCode by opening `App/BitBar.xcworkspace`. This will use the `App/Scripts/sub.1m.sh` example script and output something like

skarmavbild 2017-01-14 kl 18 37 31

## What's next

- Test quoted values, i.e `href="..."`. Implementation is done but hasn't been tested using SwiftCheck
- Better error messages
- (Re)implement 
  - The preference menus
  - Sparkle for updates
- Dynamic plugin path. The current one is hard coded
- Refactor test suit, custom matchers?
- Handle both ANSI and truncate for the same title
- The font size is a bit off right now, not really sure why

## Flow

This is the basic flow of data in the application. I tried to use the same naming convention as the existing application.

skarmavbild 2017-01-14 kl 19 18 09

## A summery

- Parser with support for
  - ANSI colors
  - Params (length, trim and so on)
  - Menus
  - Infinitive number of sub menus
- CocoaPods for dependency management
- Property-based testing using SwiftCheck
- BDD/TDD using the Quick framework
- XCode independent, using `xcpretty` for output formatting and `make watch` as file watcher
- Swiftlint compatible (`make fix` and `make lint` uses this)
- Makefile based on the [Alcatraz](https://github.com/alcatraz/Alcatraz/blob/master/Makefile) project
- Gitignore from [github/gitignore](https://github.com/github/gitignore)
- Travis-ci compatible (`make ci`) ([latest builds](https://travis-ci.org/oleander/bitbar/builds))

## Epilog

I _might_ have gone a bit overboard with this pull request. The initial idea was to fix [#379](https://github.com/matryer/bitbar/issues/379) but after spending hours with segmentation faults and other obscure errors, caused by my lack of understanding of the language, I decided to look for alternatives. After searching for "swift" in issue tracker I found a [few comments](https://github.com/matryer/bitbar/pull/40#issuecomment-168966103) from @matryer regarding migrating to Swift – so I decided to give it a go my self.

With that said I understand if this is "to much" and if you decide not to merge.

A side note; I might have removed files from the original project when simplifying the implementation a few weeks ago. If you find something that should be in the project but isn't, such as assets files, let me know and I'll add it.

~ L

### CODE REVIEW

**Comment by oleander** [comment]
skarmavbild 2017-01-20 kl 17 55 08

skarmavbild 2017-01-20 kl 18 06 51

- [ ] ANSI
  - [x] Combine with other params, such as `length`
  - [ ] Other colors and styles, such as bold and italic
  - [x] Fix invalid offset in menu bar (fixes: https://github.com/matryer/bitbar/issues/376) when using ANSI
  - [x] Support for ANSI in menu bar
- [ ] Preference items
  - [x] Reload all
  - [x] Quit
  - [x] Select plugin folder and store the result with the application
  - [ ] Open plugin folder
  - [ ] Open at login
- [ ] Descriptive error messages
- [x] Simple error messages using `:warning:`

**Comment by oleander** [comment]
skarmavbild 2017-01-20 kl 23 48 04
skarmavbild 2017-01-20 kl 23 47 58

**Comment by oleander** [comment]
The offset fix for #376 now also applies to emojis (now / before)

offset

**Comment by matryer** [comment]
This is great work!

**Comment by matryer** [comment]
There are LOTS of open PRs for the obj-C project... seems we need to make a decision about Swift vs Obj-C. @iosdeveloper, what do you think?

**Comment by oleander** [comment]
@matryer Thanks! :)

Made a quick summary of the open PRs.

- [x] [added ANSI support for 256 colors](https://github.com/matryer/bitbar/pull/364) The current implementation is based up-on <== PR. What's left is mapping each color to an ANSI number, something @iosdeveloper already did ([relevant code](https://github.com/oleander/bitbar/blob/swift/App/BitBar/Parser/Ansi.swift#L91))
- [x] [fixed font crash](https://github.com/matryer/bitbar/pull/361) Not a problem with the current parser.
- [ ] [added environment variable BitBarVersion. closes #358](https://github.com/matryer/bitbar/pull/359). Can be added [here](https://github.com/oleander/bitbar/blob/swift/App/BitBar/Script/Script.swift#L81) with a few lines of code.
- [ ] [added image loading from an URL](https://github.com/matryer/bitbar/pull/356) The current code structure and support for CocoaPods makes it fairly easy to migrate the code.
- [ ] [gray out status item during refresh](https://github.com/matryer/bitbar/pull/340) Callbacks for handling this kind of events are already implemented so it's mostly about putting everything together.
- [ ] [Do less per refresh cycle to bring down CPU usage](https://github.com/matryer/bitbar/pull/393) Not implemented.
- [ ] [Add name of macOS when referring to Mac OS X](https://github.com/matryer/bitbar/pull/385) Unrelated to this PR
- [ ] [Document nested submenus](https://github.com/matryer/bitbar/pull/371) Unrelated to this PR.
- [x] [added checkmark parameter](https://github.com/matryer/bitbar/pull/330) Already implemented.
- [ ] [Potential fix for #88: Read from a config.json file](https://github.com/matryer/bitbar/pull/326]) Not implemented.
- [x] [Support for multi-line titles](https://github.com/matryer/bitbar/pull/324) Already supported
- [ ] [added bitbar://screenshot](https://github.com/matryer/bitbar/pull/322) Not implemented.
- [x] [updated submodules](https://github.com/matryer/bitbar/pull/321) Sub modules has been replaced with CocoaPods
- [ ] [added drop to plugin](https://github.com/matryer/bitbar/pull/319) Not implemented.
- [ ] [show menu when clicking status item and pressing alt key #318](https://github.com/matryer/bitbar/pull/318) Not implemented.
- [x] [added streaming through stdout](https://github.com/matryer/bitbar/pull/317) Implemented.
- [ ] [Set working directory to folder the plugin is in](https://github.com/matryer/bitbar/pull/280) Not implemented, but only one line of code.
- [ ] [use iTerm app](https://github.com/matryer/bitbar/pull/179) Not implemented.
- [ ] [Possible fix for unicode in plugins](https://github.com/matryer/bitbar/pull/146) Not implemented, but I haven't seen any unicode problems so far. The parser doesn't work with pure strings but with the underlying Character type used to represent Unicode scalar values ([more info](https://developer.apple.com/reference/swift/character)), so there should be minimal data loss between the terminal and the GUI.

Some of the PRs from @iosdeveloper above was merged into the `beta` branch when I started a few weeks back. 

Hope that helps.

**Comment by oleander** [comment]
2 132 passing specs implemented. 2000 property based and 132 static.

**Comment by oleander** [comment]
Next update.

skarmavbild 2017-02-05 kl 03 45 47

skarmavbild 2017-02-05 kl 03 45 54

Pre-builds can be found here: https://github.com/oleander/bitbar/releases
Test suit passes here: https://travis-ci.org/oleander/bitbar/builds
I'll update with a more precise description in a few days.

**Comment by tresni** [comment]
Looking at the PRs that are not currently supported:
* Only [1 plugin](https://github.com/matryer/bitbar-plugins/blob/master/System/currentFiles.1h.rb) in matryer/bitbar-plugins uses $BITBARVERSION (but it's an easy win and provides info for plugin developers to know what features are available)
* No plugins use bitbar://screenshot (personally I don't like this PR, other tools for this)
* images from urls is not currently used (from what a quick ag/grep can see), but I think this is the right way to go.  The amount of plugins that are HUGE because they have embedded images in them is sad.
* drop to plugin (ie droptypes) is not used by any plugin

So that said I'm :+1: on getting this merged so people (like me) know what code base to work from moving forward :)

**Comment by clthck** [comment]
when will this PR merged into?

**Comment by oleander** [comment]
Just an FYI. I'm currently working on moving generic code, like the emoji parser to their own packages, otherwise there isn't much left except testing it. 

We have decided to only implement what's being documented. So support for HTML plugins wont, for example be added.

**Comment by oleander** [comment]
@tresni .1 and .3 has been implemented.

**Comment by tresni** [comment]
@oleander did you see my message in slack?

the following plugin won't render correctly on beta11.  Had trouble trying to compile master myself so haven't been able to test that:

```
#!/bin/bash

cat <<heredoc
test
---
entry 1 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
entry 2 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
Other Entries
--More Entries
----entry 3 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
----entry 4 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
--Smore Entries
----entry 5 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
----entry 6 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
--Last Subentry
----entry 7 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
---
entry 8 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
entry 9 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
---
entry 10 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
heredoc
```

None of the entry's are executable (should be) and entry 9 has an empty submenu.

**Comment by oleander** [comment]
@tresni Aha, missed that one. I'll see if I can reproduce.

**Comment by oleander** [comment]
@tresni Is that one really valid? I mean, `---` is only used as a separator between the topbar and everything else, right?

**Comment by tresni** [comment]
`---` can also be used to add a separator in the menu per [this code](https://github.com/matryer/bitbar/blob/aa4dee753105ee887b58e9ddddbbd4a539ed95ac/App/BitBar/Plugin.m#L286-L287)

**Comment by oleander** [comment]
@tresni >

The initial implementation I wrote was actually how it's implemented in objective-c, as you expected it to be. The problem was that it made the specification inconsistent and implementation way to complex. 

The current documentation defines a sub menu of level `x`, `x` times 2 dashes followed by the content. So `----A` would mean level 2 with content `A`. With the same spec, `---` would mean a submenu of level 1 with the content `-`; a divider.  Just `-` would mean a separator on level one. 

This makes the spec consistent as the dashes stills means the level of a submenu. It also makes the parser a breeze to implement as it doesn't have to take the concept of separators into consideration. It just treats it as a menu with the content `-`.

In your example you expect the parser to first check for `--` then, if another `-` treat it as a separator unless it's followed by something other the a new line, otherwise treat it as a sub menu. Basically this means that one token has two different meanings in the same context and that the order we parse them in matters. This is usually a red flag. Manly as it requires the specification to define a priority for the two tokens, which makes both the implementation, usage and specification more complex.

Considering this isn't documented, and that the next release, most likely, going be a new version with some undocumented features removed, I suggest we stay with the current implementation.

The reason you have an empty sub menu is because it treats `---` as a sub menu of level 9, consisting of only of a separator. My guess is that Cocoa treats a menu with just a separator as an empty menu, hence the behavior.

Here's the fix.

``` bash
#!/bin/bash

cat <<heredoc
test
---
entry 1 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
entry 2 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
Other Entries
--More Entries
----entry 3 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
----entry 4 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
--Smore Entries
----entry 5 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
----entry 6 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
--Last Subentry
----entry 7 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
-
entry 8 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
entry 9 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
-
entry 10 | terminal=false bash=/Users/bhartvigsen/script.sh param1=param refresh=true
heredoc
```

I'm flexible tho, so let me know what you think :)

(Had some time while waiting for the bus which is why the answer is a bit redundant and long :))

**Comment by tresni** [comment]
@oleander my slightly unscientific `grep` shows that ~112 of 312 plugins (or ~35%) use "---" on its own (indicating horizontal breaks in menus.)  As such I would argue that parsing should be kept the same or you are going to see ~1/3 of plugins break under the new code.

I did my check using the following:

```
# Look for any occurance of three hyphens followed by word breaks
# This is definitely not perfect, e.g. it would match "---- hello" but not "----hello"
grep -R -c -E "\W---\W" .
# Strip where there are 0 or 1 occurrences
# (this is the "expected" behavior per current Swift code)
| grep -v -E -e ":0$" -e ":1$" -e "^./.git"
# Count the number of files returned
| wc -l
```

A spot check of the matched lines shows the vast majority appear to be using triple dashes for separators in menus.  The following plugins were identified:

```
BitBar/version.12h.rb
Dev/Backlog/backlog-show-my-task.1m.rb
Dev/BitbucketServer/stash-pull-requests.2m.rb
Dev/Checkman/checkman.10s.rb
Dev/CircleCI/circleci-check.5m.py
Dev/Codeship/codeship.1m.py
Dev/Docker/docker-status.1m.sh
Dev/Gerrit/gerrit_incoming_crs.5m.py
Dev/GitHub/gh.5m.js
Dev/GitHub/notifications.30s.py
Dev/GitHub/repo-issues.5m.js
Dev/GoSquared/gosquared-now.30s.py
Dev/Homebrew/brew-services.10m.rb
Dev/Homebrew/homebrewcask.1d.sh
Dev/Hosting/Heroku/heroku.1m.rb
Dev/Hosting/Heroku/listapps.5m.sh
Dev/Icinga2/icinga2.24m.py
Dev/Jira/jira.1m.sh
Dev/LightSalmon/lightsalmon.12h.sh
Dev/MetaPackageManager/meta_package_manager.7h.py
Dev/Pantheon/pantheon-list-sites.1h.php
Dev/RabbitMQ/rabbitmq-status.1m.php
Dev/Redmine/redmine-show-my-task.1m.rb
Dev/RescueTime/rescuetime.1h.py
Dev/Shell/aka.1h.sh
Dev/Travis/travis-check.2m.py
Dev/Vagrant/vagrant.2m.pl
Dev/Vagrant/vagrant.30s.pl
Dev/Virtualbox/virtualbox-running_vms.30s.rb
Dev/VisualStudioOnline/vso-pull-requests.1m.js
Email/gmail-checker-improved.1m.pl
Environment/quake.1h.sh
Environment/solaredge.5m.py
Finance/ginmon.1d.sh
Games/minecraftplayers.1m.py
Games/xboxfeed.10m.js
Lifestyle/fortune.5m.sh
Lifestyle/habitica.1h.js
Lifestyle/iss.1m.sh
Lifestyle/random_quotes.5m.sh
Lifestyle/SaveToLinkPack.1h.rb
Lifestyle/taskwarrior.4m.py
Lifestyle/time_on_earth.10m.rb
Lifestyle/todo-md.30s.pl
Lifestyle/todo.15m.rb
Lifestyle/transmission.4m.py
Lifestyle/unsplash-background.3h.sh
Music/cmus.10s.sh
Music/itunes.10s.sh
Music/itunesRating.10s.sh
Music/nowplaying.5s.sh
Music/songkick.1d.py
Music/spotify.10s.sh
Music/vox.30s.sh
Network/aria2.3s.py
Network/bitping.10s.sh
Network/got-internet.2s.sh
Network/internal-ip.1h.sh
Network/netinfo.60s.sh
Network/network-location.1h.sh
Network/pi-hole.1m.py
Network/ping.10s.sh
Network/vpn_advanced.sh
PIM/todotxt.15s.sh
Politics/five-thirty-eight.15m.rb
Sports/bundesliga.1h.py
Sports/live_cricket.2m.py
Sports/live_tennis.1m.py
Sports/SpursBar.6h.rb
System/adobe-flash-update-check.60m.py
System/caffeinate.1h.sh
System/clipboard-history.3s.sh
System/ColorfulBatteryLevel.5s.sh
System/copy-to-clipboard.sh
System/currentFiles.1h.rb
System/DarkModeToggle.sh
System/downloads.1h.sh
System/ejector.5s.sh
System/host-switcher.1d.sh
System/launch-agents.10s.sh
System/mdf.1m.sh
System/mtop.5s.sh
System/mysql-status.1m.sh
System/postgresql-status.1m.sh
System/usbInfo.10s.py
System/virtualbox-vms.5s.sh
Time/alarmclock.1s.sh
Time/googlecal.30m.js
Time/shiftstats.30s.py
Time/stopwatch.1s.sh
Tools/Catchpoint/catchpoint.m5.php
Tools/Keybase/keybase-encrypt.10m.rb
Tools/octoprint.1m.sh
Tools/PagerDuty/pagerduty.30s.rb
Tools/statuspage.1m.rb
Travel/gwr-wifi-status.1m.py
Travel/travel-time.5m.php
Tutorial/ansi.sh
Tutorial/emoji.sh
Tutorial/submenus.sh
Weather/FlagoftheCharles.15m.rb
Weather/ForecastIO/weather.15m.py
Weather/Wunderground.30m.rb
Web/EasyDigitalDownloads/edd.15m.py
Web/HackerNews/hacker_news.1m.rb
Web/Instagram/igs.10m.py
Web/ProductHunt/producthunt-tech-hunts.1d.py
Web/putio.5m.py
Web/Reddit/redditnotify.30s.py
Web/trello.15m.sh
Web/Twitch/livestreamer-now-playing.5m.js
Web/Twitter/twitter.1m.py
```

**Comment by oleander** [comment]
@tresni You're right. It looks a bit to risky to remove the support at this stage. I reimplemented the functionality and push a new version. Also migrated over to [fastlane](https://docs.fastlane.tools/)  to easier manage new builds, signing and tests.

Automatic, signed builds from master can be found here https://github.com/oleander/bitbar/releases

Here is a guide on how to set everything up.

1. `git clone https://github.com/oleander/bitbar.git && cd bitbar`
2. `make setup`
3. `fastlane build`
4. `open BitBar.app`

**Comment by tresni** [comment]
@oleander I'll try to test today. The other behavior was that `terminal=false refresh=true bash=Something` lines weren't clickable. Not sure if this fixed that but I'll let you know :)

**Comment by oleander** [comment]
That's fixed as well! :)

[image: Linus Oleander]

*Linus Oleander* / CEO

*Oleander Development AB*
+46 76 561 61 67 / http://oleander.io

[image: Facebook] <https://www.facebook.com/linus.oleander> [image: Twitter]
<https://twitter.com/linusoleander> [image: Github]
<http://github.com/oleander>

På 18 april 2017 kl. 01:57:28, Brian Hartvigsen (notifications@github.com)
skrev:

@oleander <https://github.com/oleander> I'll try to test today. The other
behavior was that terminal=false refresh=true bash=Something lines weren't
clickable. Not sure if this fixed that but I'll let you know :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matryer/bitbar/pull/391#issuecomment-294590949>, or mute
the thread

**Comment by oleander** [comment]
A lot of updates since last time I posted.

- URL handle `openPlugin` and  `refreshPlugin` has been added.
- A proper updater is now in place pointing to the same host as the original app.
- Instruments has been used to reduce reference cycles and other memory leaks.
- `ServiceManagement` is now used to implement 'open on login'. This is the new method post 10.11.
- A lot of code has been extracted out from the project, like the Ansi & Emoji parser. This makes maintaining the core business logic much easier. It also reduced the number of LOC with about 1k.
- A DSL for verifying the menu implementation has been implemented. It looks something inline with `expect(menu, when: .clicked).toEventually(have(.broadcasted([.refreshPlugin])))` and can be found in `Tests/ExecutablePluginTests.swift`.
- Errors from background scripts are now displayed directly in the menu (see print screen).
- Both the static preference menu and dynamic menu generated from stdout are now tested (see `Tests/ExecutablePluginTests.swift`).
- Performance heavy operations, such as parsing the output and downloading images, are now set to run in its own threads. This makes the UI smoother.
- Invalid input, such as defining a `param1="..."` but not a script `bash="..."` results in an error message which is displayed in the menu.
- Images defined using `image=http://...` are now cached using [AlamofireImage](https://github.com/Alamofire/AlamofireImage), which means that they are only downloaded once while the application is running.

err

Give it a try and see if it works as expected. https://github.com/oleander/bitbar/releases/tag/untagged-1222367e5064858e6fc0

**Comment by plessbd** [comment]
@oleander not sure if this is something we want to fix with your swift build or the library I am using but I have found a "bug"

the library I am using is https://github.com/sindresorhus/bitbar/ it currently outputs lines that end in | and with the values of the key values in quotes
```
:+1: Test|color="green" emojize="true"
---
:thumbsup:  link|href="https://openxdmod-fed-ub-chemistry.ccr.xdmod.org/" color="green" emojize="true"
uptime: 20:39:05|
```

this causes the swift version to break. The non swift version works without issues.
I am not sure if you are trying to keep everything working 100% or if changes should be made after this version is adopted to the library to make it compliant with the new way, but I wanted to put it out there.

**Comment by oleander** [comment]
skarmavbild 2017-05-27 kl 17 06 28

skarmavbild 2017-05-27 kl 17 06 20

skarmavbild 2017-05-27 kl 17 07 44

**Comment by iosdeveloper** [comment]
I think it would be helpful to visually compare every plugin from the plugins repo between yours and the main repo to see if they still work. I did that before using `bitbar://screenshot`: https://github.com/iosdeveloper/ScreenshotTest/blob/all-plugins/screenshot.sh

**Comment by tresni** [comment]
Latest untagged (untagged-29a9437216657d85a74c) fails to start at all if something else is using port 8080 (had a docker stack I was testing that did and BitBar would silently fail.)  Older builds seemed okay with this so not sure what the change is.  But using 8080 is a bad idea, that's a really commonly used port.  Either allow the user to change it (plist?) or use an unassigned port (or request an assigned one?)

```
» /Applications/BitBar.app/Contents/MacOS/BitBar
Could not load config files from: /Users/travis/build/oleander/bitbar/Packages/Config/
Try using the configDir flag
ex: .build/debug/Run --configDir=/absolute/path/to/configs
The default hash should be replaced before using in production.
The default cipher should be replaced before using in production.
No command supplied, defaulting to serve...
Starting server on 0.0.0.0:8080
Serve error: Sockets Error: Failed trying to bind to the address

Identifier: Sockets.SocketsError.bindFailed
```

**Comment by oleander** [comment]
@tresni That's why I haven't merged master with the swift branch – its not ready to be used by any other then me :) Port 8080 is currently used for this. More info later this week.

skarmavbild 2017-06-13 kl 18 31 57

skarmavbild 2017-06-13 kl 18 34 16

**Comment by oleander** [comment]
While am at it;

skarmavbild 2017-06-13 kl 18 36 30

The two on the left are BitBar items. The second one contains an error shown above. The height, alignment, font and colors are now correct.

skarmavbild 2017-06-13 kl 18 36 35

**Comment by oleander** [comment]
@plessbd Incase you didn't see the 'heart' on your comment; your suggestion was merged into oleander/bitbar a few days after your post. You are now allowed to use zero or more params for a menu, i.e `--Menu|`. Thanks for the input!

**Comment by oleander** [comment]
Maybe I should just post what I've been up to instead of waiting until i merge with this branch. Here's what I can remember right now.

- Cyclic menu is now implemented
- 20-ish customized error messages for everything from invalid bash files to duplicate param to defining a param but not a script. See `Errors.swift` for more info.
- Support for config files in the INI format according an older issue
- A new file type (?) `stream` as in `file.stream.sh` for files that are not suppose to terminate. On my way to implement `static` for scripts that are only suppose to run once.
- A fully working CLI implemented using websockets and an HTTP server as the example above shows. Supports live streaming of log messages. Build on-top of Vapor which exposes a really nice DSL. The implementation is only 50 LOC + the CLI – thanks for Vapor.
- Better log messages for debugging using SwiftyBeaver. Messages are categorized into VERBOSE, ERROR, WARNING and INFO.
- Persistent storage for plugins as well as the ability to invoke plugins with arguments from the command line `bitbar plugin:invoke timer.1h.js arg1 arg2`.
- Icons (like the bug shown in the example) are now shown as images instead of text. This fixes the problems with alignment.  octicons.github.com is the current icon set being used
- Metadata is now parsed on start up and placed within the plugin. Posted an example of this a few weeks ago.
- The source code now supports both the Swift Package Manager and Cocoapods.

There are more features and fixes, but I can't recall them right now. I'll update the PR if I do.

**Comment by plessbd** [comment]
@oleander AWESOME.

I am looking forward to what you are doing with socket.io. I actually have a service monitored via nodejs that would benefit from that.  Instead right now it runs every 10 seconds via a bash script, since in the old version I couldnt use nodejs directly (and I have not bothered trying to get it to work directly since)

Keep up the great work!

**Comment by oleander** [comment]
- The parser supports escaped characters, so quoted fields can now look like `bash="/bin/echo \"Hello\""`. You can also mix different quotes, like `bash="/bin/echo 'Hello'"`. The same goes for the `|` delimiter (and every other special character used in BitBar) `--Menu \| More| bash="..."`.
- The `bash` param now accepts inline scripts like `bash="ls | grep -i dot"` and `bash="echo" param1="Hello"`. It supports, as far as I can remember, shell builtins (like `echo`), absolute paths (like `/bin/echo`),  scripts in your `$PATH` (like `rvm`) and shell aliases. 
- The order items occur in the menu bar are now persisted (OS X 10.12+). A plugins position is bound to its absolute path. If a plugin is moved or renamed it will placed wherever Cocoa thinks it fits in.
- Installing a plugin from the website now refreshes the menu bar.

**Comment by oleander** [comment]
@tresni Just deployed a new version where you can set the port number using `BitBar.plist` for production (`9112`), testing (`9110`) and development (`9111`). Default ports within parentheses. Thanks for feedback!

- Download: [BitBar.dmg](https://github.com/oleander/bitbar/releases/download/untagged-5e6a6a808250d1f5c371/BitBar.dmg)

skarmavbild 2017-06-18 kl 21 56 04

@plessbd Just for clarification; the app is decoupled from socket.io. The example I showed above was just an example error message that happened contain socket.io. 

That said, the streaming support in this version is really good which enables you to do some cool event driven stuff without requiring a server/client like socket.io. I manage to reduce a node.js plugin previously build on-top-of socket.io with about 70%. BitBar takes care of most things for you (like inter process communication (CLI <=> Socket, Plugin <=> CLI), keeping the server alive, restarts, data persistence, error handling, port collisions, and so on), which is really neat. I'll see if I can post a few examples during next week. 

Feel free to give the new version a try. I'll integrate the CLI into the GUI next week.

**Comment by russelg** [comment]
Would it be possible to add the dimming feature when multiple monitors are involved? 
This is what it looks like while active, which is fine. 
screen shot 2017-06-19 at 1 55 00 pm

However, it looks like this on a dimmed menu bar:
screen shot 2017-06-19 at 1 56 14 pm

It would be great if an environment variable which behaves like `BitBarDarkMode` was provided. Maybe `BitBarInactive` or something?

**Comment by oleander** [comment]
There is no longer (and hasn't been since Februari's release) any limitation on the number of arguments passed to `bash`. 

I.e `bash="ls" param1="1" ... param99="99"` now yields `ls 1 ... 99`, where `...` is `param2` up to `param98`. The params are now also sorted by their id, so  `bash="ls" param99="99" param1="1"` yields `ls 1 99`.

**Comment by oleander** [comment]
@russelg If you dig up the necessary API docs I'm happy to implement it. If not, wait a few weeks and I'll get to it :)

**Comment by russelg** [comment]
@oleander I'm not an OSX developer so I can't be sure, however this may be relevant for detecting if the item is inactive or not:

https://developer.apple.com/documentation/appkit/nsstatusbarbutton/1409292-appearsdisabled
`NSStatusBarButton.appearsDisabled` may be of relevance (for detecting the dimming).

Code for fixing/adding `BitBarDarkMode` is of course already in the original BitBar code here.

**Comment by plessbd** [comment]
@oleander Great work.

I was wondering if you could provide some more examples, like the streaming stuff your doing as well as how to use the cyclic menu

Again, love the improvements you are making.

**Comment by oleander** [comment]
The latest version now bundles the CLI. Install it via the setting panel (see print screen)

skarmavbild 2017-06-23 kl 11 27 06

[Latest BitBar.app build](https://github.com/oleander/bitbar/releases/download/untagged-2270dee629c5b44fc450/BitBar.dmg).

@russelg @plessbd I'll get back to you guys in the end of the week.

**Comment by palmerj** [comment]
I just tried this and the on 10.12 and the application keeps quitting and falling our of the menubar. Has anyone else had this problem?

**Comment by oleander** [comment]
@palmerj That's fixed in the latest, currently not deployed, but pushed, version. Stay tuned!

**Comment by palmerj** [comment]
Ok thanks. Any idea on when a new version will be release. If it's not planned soon, I will revert to the official bitbar for now.

**Comment by fazibear** [comment]
Any updates ?

**Comment by oleander** [comment]
Long story short; I'm currently doing a bike tour since two months back from London to Iran. Don't have that much time any more to work on this. I do still work on it, but its going a bit to slow. The project has been stable a few times in the past since I made the fork, but since I didn't get any feedback I continued adding features - which made it unstable - and thats where we are right now.

I see two options that doesn't involve throwing the project away. 

1. Finding a commit prior to `HEAD` that implements as much, if not all functionally of `matryer/bitbar` and continuing the development from there.
2. Continuing from `HEAD` and fixing whats currently broken. This will you give an array of new features that as been requested for years (that's how I decided what features to include, I looked at the issues).

I sincerely hope that my fork isn't thrown away and forgotten considering the 1000 of hours spent on it. Last time I checked in May I had 1200h (according to wakatime.com) - and thats only the editing part. 

I cant promise anything, but I probably gonna continue on this fork when I reach Iran as I use my version of BitBar every day.

21743039_1959121557666874_5454914103067717631_n

**Comment by plessbd** [comment]
@oleander Congratulations on your bike tour, it sounds amazing.

I use your version daily and also don't want to see it disappear.

It has been updated more recently than than this version and does have many fixes and features that have helped me.

I dont know enough swift to help out, but will continue to use and offer any feedback that I can.  Keep up the good work and if nothing else I would appreciate a stable release that even if it doesnt get any enhancements just continues to work with the newer versions of macOS (since High Sierra is coming out in a couple weeks) I would be happy.

**Comment by unrzn0** [comment]
Hi, just tried your version (from source and as dmg) - and the code seems to be not compatible anymore to latest Xcode versions - and it also aks for an upgrade to Swift4. The dmg then seems to refer to some dylibs from Xcode, which I think a casual user wouldn't have installed and also some symbols seem to have changed (maybe because of Swift4). I myself never did Swift, but I think if you'd make it compile again ans bundle a complete dmg with all dependencies, barrier for users would be lower to look into the code and fix what's broken (if anything is broken).

**Comment by matryer** [comment]
If you’re interested in contributing, I think this branch needs some love. Maybe even a rewrite if the language has evolved far enough along. 

Mat

**Comment by oleander** [comment]
I’m still biking so won’t have time to work on the project as it is now. In Iran right now and is heading to New York so have a few years left on the road. 

There are at least 40 previous versions that are stable and implements everything that’s in the objective-c version + bug fixes and tests. Which commit is stable I’m not sure as i haven’t worked on the project for half a year. Master currently implements an array of new features which isn’t in the objective-c version - some of them unstable which is why the application isn’t working atm. Never planed to stop working not the project cold turkey, hence the crashes. 

Spent about a thousand hours on the project last year. If you have the time, feel free to do it again :) I would try to find a stable commit and work from there. That would take a fraction of the time it would to rewrite it - again. I especially recommend you (the reader) to look at the LL parser - the core of the application, as this is where the majority of the time was spent. 

I might have time to work on the project for 10 ish hours when I get to the capital as I’m staying there for two weeks while the bike is being fixed. I can take a look at it then, if any of the admins are interested.

I’m waiting to hear from Mat. 

// Linus

> 8 feb. 2018 kl. 15:47 skrev Mat Ryer <notifications@github.com>:
> 
> If you’re interested in contributing, I think this branch needs some love. Maybe even a rewrite if the language has evolved far enough along. 
> 
> Mat
>

**Comment by jannik-mohemian** [comment]
@matryer @oleander What is the status on this? Would love to see progress using this branch/version...

_Also using oleander's version_

**Comment by matryer** [comment]
@jannik-mohemian It's stalled at the moment. I'm in search of new maintainers.

**Comment by gingerbeardman** [comment]
@oleander where are you right now? did you look at this recently?

**Comment by mpicard** [comment]
Is there anything missing to merge this? @oleander @matryer can we get an update? I don't know Swift but we could merge and close a bunch of issues and "start fresh" so to speak with Swift

**Comment by gingerbeardman** [comment]
@mpicard @matryer I think nothign has changed since the comment above https://github.com/matryer/bitbar/pull/391#issuecomment-364102193

Happy to help go through the commit logs and test builds to find the last stable release that was feature complete

**Comment by mpicard** [comment]
@gingerbeardman I'd love a little code walk through since I'm not familiar with Swift but since you seem to have fixed a lot of bugs and stuff I'd be really nice to merge this, pending @matryer approval as well. Let's schedule a Zoom soon so reach out at martin8768#gmail#com

**Comment by gingerbeardman** [comment]
@mpicard the fork is not mine, it is by @oleander who is travelling around the world on a bike

**Comment by oleander** [comment]
I'm still biking. 25 000 km in but I'm willing to help.

IMG_6858

**Comment by eldemcan** [comment]
I hope it is possible to merge contributions of @oleander 🤞 . Best of luck in your journey.

**Comment by kdeldycke** [comment]
FTR, there is an alternative Swift-based project too BitBar, and seems to be actively maintained: https://github.com/swiftbar/SwiftBar

**Comment by gingerbeardman** [comment]
SwiftBar (above) is currently 10.15+ only

**Pull request closed without merging**
