### PR TITLE
Possible fix for unicode in plugins. Fixes #141

### LINKED ISSUE #141: Text encoding
I have some spanish text, how can I show them?, I get something like this in the dropdown:

Bajo el m?\195?\161ximo de CPUs de 8 a 6

And the correct text would:

Bajo el máximo de CPUs de 8 a 6

I'm using bash.

Thanks,

### PR DESCRIPTION
**Pull request by jtokoph**
Possible fix for #141
I'm a total Objective C noob, but I think I got this working.

The locale loads properly on my machine, but I don't know how it will work in all environments.

### CODE REVIEW

**Comment by matryer** [comment]
LGTM - does anyone else want to review this before we go with it?

**Comment by jtokoph** [comment]
Actually, I may change with a cleaner way in a minute.

**Comment by jtokoph** [comment]
2 am brain forgot that self.manager.environment was already setup with an extra environment variable (BitBar).

Just added the locale variable to that same code path.

**Comment by taylorzane** [comment]
You may also want to check if `$LANG` is defined. The optimization is certainly negligible, but if you don't have to set an extra env var, why do it?

**Comment by 303936054** [comment]
????

**Comment by matryer** [comment]
What's the status of this? @iosdeveloper do you have a view?

**Comment by iosdeveloper** [comment]
I don't think this should be a fix in the app.

**Comment by jtokoph** [comment]
Seems weird to me that every plugin will have to pick a locale itself in order to display unicode.

**Comment by iosdeveloper** [comment]
It is consistent with our PATH handling though.

**Comment by jtokoph** [comment]
Do you know of a way for a plugin to detect the proper locale instead of just picking an arbitrary one?

**Comment by iosdeveloper** [comment]
This works for me:
```#!/bin/bash
echo $(/usr/bin/defaults read -g AppleLocale)```

**Comment by tresni** [comment]
Just like PATH I think this should be fixed in the app.  It's crazy that we are requiring every plugin author and user to change every plugin they may want to use to deal with something that could be simply in the code (the UTF-8 bit is super simple to do in the code, PATH handling would likely require reading some option but still.)

**Comment by mherger** [comment]
Thanks for the 'defaults' trick. That should help me overcome this issue. 

But as most of the other voices here I'd really hope this could be fixed in the app. Localization shouldn't be treated like a disease :-).

**Pull request closed without merging**
