### PR TITLE
Set working directory to folder the plugin is in

### PR DESCRIPTION
**Pull request by tresni**
This changes the working directory for plugins from the app folder to the plugin folder.

### CODE REVIEW

**Comment by matryer** [comment]
Hmm, I'm not sure. What does everyone else think?

**Comment by ibutra** [comment]
For me it is exactly the opposite feeling. I think it is much more intuitive to have the working directory where the script resides. This also allows for files in subfolders of the plugin folder to be easily referenced. And I wouldn't like to have some complimentary scripts in my application folder.

**Comment by tresni** [comment]
It is settin it to the folder where the script resides. But right now that is always the main plugin folder so..  But yeah, same feeling on my side. Much rather have it go where the script is then where the application executable is.

**Comment by vogonistic** [comment]
I feel like the value of this really starts when, assuming we will, support plugin bundles.

**Comment by vogonistic** [comment]
@tresni You should edit the first comment and make it clear that the PR changes the CWD from the app to the plugin folder. I misunderstood it until I read the commit.

**Comment by tresni** [comment]
@vogonistic done and agree on this being more useful if/when we support plugin bundles.

**Pull request closed without merging**
