### PR TITLE
added streaming through stdout

### LINKED ISSUE #121: Streaming through stdout
Is it possible to stream stuff instead of rerunning a script every few seconds?

I have an implementation but all I see is 'BitBar ...'

Great project btw! I've been trying to write something like this for ages but always got stuck.

### PR DESCRIPTION
**Pull request by iosdeveloper**
closes #121

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Might want to merge this into a branch `v2`.

**Comment by captncraig** [comment]
Any update on taking this? I would really like to make an app that supports this for streaming updates.

**Comment by iosdeveloper** [comment]
You can use v2 beta today: https://github.com/matryer/bitbar/releases/tag/v2.0.0-beta10

**Comment by matryer** [comment]
We are going to do a review of all new functionality soon. This included.

**Comment by selvakn** [comment]
@iosdeveloper : it works great. 

One minor problem though.
The content is not getting refreshed when the menu is open.
Not sure if it can be fixed, but it would be great if it can be.

**Comment by iosdeveloper** [comment]
@selvakn Please open a new issue for this as the "problem" exists on master too.

**Comment by exside** [comment]
Another issue I'm seeing is that somewhere is a memory leak, at least the way I'm using it, basically JavaScript/Deno connecting to a websocket, streaming data and console.log() updates in the BitBar format...over time Bitbar consumes several 100MB of memory (starting at around 5.5MB in my case), so I have to kill it and restart it every few days (it actually depends on how much data comes in). I suspect is some kind of issue with all the console.logs() accumulating in the background, I tried to console.clear() etc. with no success so far... any ideas?

**Pull request closed without merging**
